version: '3.8'

services:
  cassandra:
    image: index.docker.io/library/cassandra@sha256:b5cde1e2b16451fa511e4a1cda4177853903879f9bab0b8f27445451a07f7ef7 # 3.11
    ports:
      - "9042:9042"
      - "9160:9160"
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5
         
networks:
  cassandra-net:
    driver: bridge
