codecov:
  notify:
    require_ci_to_pass: yes
    after_n_builds: 3
  strict_yaml_branch: main  # only use the latest copy on the main branch

ignore:
  - "**/*.pb.go"
  - "**/*-gen/*"
  - "**/mocks/*"
  - "**/thrift-0.9.2/*"

coverage:
  precision: 2
  round: down
  range: "95...100"
  status:
    project:
      default:
        enabled: yes
        target: 95%
    patch:
      default:
        enabled: yes
        target: 95%
