issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters: [gosec, bodyclose]

    # See https://github.com/jaegertracing/jaeger/issues/4488
    - path: internal/grpctest/
      linters: [staticcheck]

    - linters: [gocritic]
      text: "dupArg"
    - linters: [gocritic]
      text: "exitAfterDefer"
    - linters: [gocritic]
      text: "appendAssign"
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable:
    - errcheck
  enable:
    # Plain ASCII identifiers.
    - asciicheck

    # Checks for dangerous unicode character sequences.
    - bidichk

    # Checks whether HTTP response body is closed successfully.
    # TODO enable this but maybe find a way to disable in tests.
    - bodyclose

    # Check whether the function uses a non-inherited context.
    - contextcheck

    # Check declaration order of types, consts, vars and funcs.
    - decorder

    # Checks if package imports are in a list of acceptable packages.
    - depguard

    # Check for two durations multiplied together.
    - durationcheck

    # Checks `Err-` prefix for var and `-Error` suffix for error type.
    - errname

    # Suggests to use `%w` for error-wrapping.
    # TODO enable this. Curently fails in about 20 places.
    # - errorlint

    - gocritic
    - gofumpt
    - goimports
    - gosec
    - govet
    - misspell


linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - io/ioutil
    packages-with-error-message:
      - io/ioutil: "Use os or io instead of io/ioutil"
  goimports:
    local-prefixes: github.com/jaegertracing/jaeger
  gosec:
    # To specify a set of rules to explicitly exclude.
    # Available rules: https://github.com/securego/gosec#available-rules
    excludes:
      - G104
      - G107
      - G404
      - G601
  gosimple:
    go: "1.20"

run:
  go: "1.20"
  timeout: 20m
  skip-dirs-use-default: false
  skip-dirs:
    - mocks
    - thrift-0.9.2
    - .*-gen
  skip-files:
    - ".*.pb.go$"
