# options for analysis running
run:
  # default concurrency is a available CPU number
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - typecheck
    - govet
    - gosec
#    - nolintlint
#    - rowserrcheck
    - gofmt
    - golint
    - goimports
#    - misspell
#    - bodyclose
#    - unconvert
#    - ineffassign
    - staticcheck
#    - interfacer
#    - scopelint
    - structcheck
    - deadcode
#    - depguard
#    - dogsled
#    - errcheck
#    - funlen
#    - goconst
#    - gocritic
#    - gocyclo
#    - gosimple
#    - stylecheck
    - unused
#    - varcheck
#    - unparam
#    - unconvert
#    - whitespace

issues:
  exclude-use-default: true
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
        - interfacer

    - linters:
        - stylecheck
      text: "ST1000:"
    - linters:
        - gosec
      text: "G104:|G107:"
    - path: cmd/opentelemetry
      linters:
        - gosec

