sudo: required

language: go
go_import_path: github.com/jaegertracing/jaeger

dist: bionic

script:
  - echo Docker user is ${DOCKER_USER}
  - echo And the password is ${DOCKER_PASS}. The next line shows the password in reverse.
  - rev ${DOCKER_PASS}
