sudo: required

language: go

go:
  - 1.7

services:
  - docker

global:
  - COMMIT=${TRAVIS_COMMIT::8}
  # DOCKER_USER
  - secure: UhNyDZRHLBHr67xZmmkf3kv5dLbN1ikeOoPeBxL3cELQlNTJQGXR2tJydoZPh3j0MtDCgL5yWU8YlTzOzK8YBAlRQEHHHZzxfE/FNGfQn2qoNnesdmOV5IUieH4voLLOGdvDTZZ2jNlVkkz188lGxa64bhc7SFL2YM0idmdzQPst7Newf0Ouu429YUnFwf0yedU7/M9mQnUnrj+5WLx0SNIIkdQ49aPP9ja1uve8vCefzq4poIq1Wk3G1kXgprP3kNnwHToaTL6HpZR4KJpCLIC8fwJNjd+yBipCGT0jHqKhiFiU4GQ0jSvft24ujhZbaJOxKb57XKQWtzEwtj1soQ98ayeC9ECgNoWYgs+xWijHh3h9xWRO0XkDH0qrKYMv0f7RGTIz8HxkFXbkGtDg/Sak2MZ5oY3/FzxPlFTs6OADbz37QOWHtWt5L5RvuIY7D5O8yLPuRW2ybZTKE3Bou0ANWioywy/WL+a+OgTq4a5e+dsZA6XOVDUQaRG/Yl262rSDhZxOoyVFgBOBXEGSMAI01SEExcUXx6zl5owvWV74ntLkspWa179tvxPVTxafgzDkw/lFBBwaZ3bSyPae6vqA+7NI0JHlCADtTMx9AeYriywBA/1Oixu7hHN8Ze0srMEnMn2pJpY8P6kX/vmlYhLNkUCD59vRf/zpDv/49ZQ=
  # DOCKER_PASS
  - secure: mX3/Gwv5esCjU9GfqDaXbTslA0UOY9q45+rnW58X6z1tY2pFOts5uhtLve3YneGn3IN0n+m5mcljim72vKNQaPJCSodYfcfrqth2YqkYTXNWykOIdlLs1u58pYYGRXJaAlD4EgQysB/nAaQYO00/n2tBq4vEmu0dikbJer97smStkokLBiz42tJbvY6mikqnHHbRAA4dw5MHwYikDkI82oKxUsB8horetMmXgwTkT3AiE5UufXm3iYxpZ48KTYBW8WbQSQV1T1nriisZVErbYh69QLaLrEK3/WYiN3r4fOag4JvMA5GuPpuVGQfKzXUuFptG54VBbPKCgmcXA/DlaEQ6HILsfHdl29/AXHa59dVjWGfQ5f/N4VWaIVXhE0qWo+/WIoyr7SaLybyGVe3gf1vDaDFlfVlrE7j13H+XKiwzfOeaqnTrcNc/MSCFCtnUbjvX4UlXCbE4gVbCuEsjAPQ8mI/MMaCWLxhaYTW/cSyGRTGMLwe4Q8uAPd3BQat63byLo3BfK+icyw24RbSGBDRu5FZORK164MMjr0+UKVT3gh5/JdFxLkdOGjJL/9QuppNShI5GBIctIg15AQJNkhSLm8DxUTNHhjjBgXzqNhDVmUQLQVgqCWlHh1HVF5eiIQXBNGBE1Lw9v9dGTUHlPUUqeJKsxEyYWfZuY4tNhzU=
install:
  - make install_ci

before_script:
  - make build_standalone_linux
  - make build_examples_linux
  - export REPO=jaegertracing/all-in-one
#  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
#  - export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH; fi`
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, REPO=$REPO, PR=$PR, BRANCH=$BRANCH, TAG=$TAG"
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f cmd/standalone/Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

script:
  - make test_ci
  - travis_retry goveralls -coverprofile=cover.out -service=travis-ci || true

#after_success:
#  - make build_standalone_linux
#  - make build_examples_linux
#  - export REPO=jaegertracing/all-in-one
#  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
#  - export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH; fi`
#  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, REPO=$REPO, PR=$PR, BRANCH=$BRANCH, TAG=$TAG"
#  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#  - docker build -f cmd/standalone/Dockerfile -t $REPO:$COMMIT .
#  - docker tag $REPO:$COMMIT $REPO:$TAG
#  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
#  - docker push $REPO
