sudo: required

language: go
go_import_path: github.com/jaegertracing/jaeger

dist: bionic

matrix:
  include:
  - go: "1.15.x"
    env:
    - TASKS=TESTS,COVERAGE
  - go: "1.15.x"
    env:
    - TASKS=PROTO_GEN_TEST
  - go: "1.15.x"
    env:
    - TASKS=ALL_IN_ONE
  - go: "1.15.x"
    env:
    - TASKS=CROSSDOCK
  - go: "1.15.x"
    env:
    - TASKS=CROSSDOCK_OTEL
  - go: "1.15.x"
    env:
    - TASKS=DOCKER,DEPLOY
  - go: "1.15.x"
    env:
    - TASKS=ES_INTEGRATION_TEST
  - go: "1.15.x"
    env:
    - TASKS=ES_OTEL_INTEGRATION_TEST
  - go: "1.15.x"
    env:
    - TASKS=KAFKA_INTEGRATION_TEST
  - go: "1.15.x"
    env:
    - TASKS=CASSANDRA_INTEGRATION_TEST
  - go: "1.15.x"
    env:
    - TASKS=MEM_AND_BADGER_INTEGRATION_TEST
  - go: "1.15.x"
    env:
    - TASKS=HOTROD

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.8.0
    - COMMIT=${TRAVIS_COMMIT::8}
    # override default yarn
    - PATH=$HOME/.yarn/bin:$PATH

install:
  - docker rmi $(docker images -q) || true
  - travis_retry make install-ci
  - |-
      case $TASKS in
        ALL_IN_ONE)
          bash ./scripts/travis/install-ui-deps.sh
          ;;
        DOCKER,DEPLOY)
          bash ./scripts/travis/install-ui-deps.sh
          ;;
        CROSSDOCK)
          bash ./scripts/travis/install-crossdock-deps.sh
          ;;
      esac

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - |-
      case $TASKS in
        TESTS,COVERAGE)
          make test-ci
          ;;
        PROTO_GEN_TEST)
          make proto
          git diff --name-status --exit-code
          ;;
        ALL_IN_ONE)
          make create-baseimg-debugimg
          bash ./scripts/travis/build-all-in-one-image.sh
          ;;
        CROSSDOCK)
          travis_retry bash ./scripts/travis/build-crossdock.sh
          ;;
        CROSSDOCK_OTEL)
          travis_retry make build-crossdock crossdock-otel
          ;;
        DOCKER,DEPLOY)
          bash ./scripts/travis/build-docker-images.sh
          bash ./scripts/travis/upload-all-docker-images.sh
          make build-all-platforms
          ;;
        ES_INTEGRATION_TEST)
          travis_retry bash ./scripts/travis/es-integration-test.sh
          ;;
        ES_OTEL_INTEGRATION_TEST)
          travis_retry bash ./scripts/travis/es-integration-test.sh
          ;;
        KAFKA_INTEGRATION_TEST)
          travis_retry bash ./scripts/travis/kafka-integration-test.sh
          ;;
        CASSANDRA_INTEGRATION_TEST)
          travis_retry bash ./scripts/travis/cassandra-integration-test.sh
          ;;
        MEM_AND_BADGER_INTEGRATION_TEST)
          travis_retry make mem-and-badger-storage-integration-test
          ;;
        HOTROD)
          bash ./scripts/travis/hotrod-integration-test.sh
          ;;
      esac

after_success:
  - |-
      case $TASKS in
        TESTS,COVERAGE)
          mv cover.out coverage.txt
          bash <(curl -s https://codecov.io/bash)
          ;;
      esac

after_failure:
  - |-
      case $TASKS in
        CROSSDOCK|CROSSDOCK_OTEL)
          make crossdock-logs
          ;;
      esac

before_deploy:
  - |-
      case $TASKS in
        DOCKER,DEPLOY)
          bash ./scripts/travis/package-deploy.sh
          ;;
      esac

deploy:
  provider: releases
  api_key:
    secure: P3+TKR3y4S51jjMp4l9kRm5cjr7Mg2m5rlPcRCjjVp/mVgkkhsMx9K8Rj/Cv/pJe33jbkwRy020gq4lYpa+Yh+Q3A11z3EKXyqizwqsvJtufoIXxXCxt0kLXn8aIh7aLrqVT2wxtkv3RvkRODmLZqvWG4kAfNBuzpcFhstw1RU3WNyahStOgwVJ9tYRdpsJ0ztMmGgQFpT6bppselzEXY7hS7L+l/bLcH9aGON4YECupAE6EilWwGxPs4oLJPmGsWQNogb3SE/oeFDqEJzciWcObk264fwIBf28HtmszQSmVbOuOfg/OhcVg13OvPXmRGk9hvU2kyzehMLZ0zeEE1mKsGmoObziNVuYPPY3KbRlsYARX41M1QKAI1YFe9NIXC5yhemOy4Xv0g82jyZmYWrf6QydLBZWkztUL7mJ6DkrG+5EohVVC2oprBS32/w736f8AWwHJSfL/JrFMTDctdYzUaf0yZMdfKdLdRyP/Q5KTfhUJl8zHAOih8f23WJVCSlwyJBYDzkq5OmNGf7BxJYkJExUOUwXcJE9jYgXq0y291N9BtG2cUVKhZZsSSrvR32bMtYtTT2a3ZlTHJpzVI+lZStYDpE/wyJRqnjqf9p8bDxc1l2mQGSxgyY8Yv8u9c+RCCj4tRwZTrJ4LIBWecDPS5hobV3Q1Dg3sW2UGRXA=
  file_glob: true
  file:
    - deploy/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: jaegertracing/jaeger
    branch: master
