version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:1.3.9
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
      - "9600:9600"
