name: 'Setup Node.js'
description: 'Setup Node.js version as required by jaeger-ui repo. Must be called after checkout with submodules.'
runs:
  using: "composite"
  steps:
    - name: Get Node.js version from jaeger-ui
      shell: bash
      run: |
        echo "JAEGER_UI_NODE_JS_VERSION=$(cat jaeger-ui/.nvmrc)" >> ${GITHUB_ENV}

    - uses: actions/setup-node@eff380dfbcf941bf8832e4acb788cebe13dfd758
      with:
        node-version: ${{ env.JAEGER_UI_NODE_JS_VERSION }}
        cache: 'yarn'
        cache-dependency-path: jaeger-ui/yarn.lock
