service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch]
      exporters: [jaeger_storage_exporter, spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics] 
      exporters: [prometheus] 


extensions:
  jaeger_query:
    trace_storage: memstore

  jaeger_storage:
    memory:
      memstore:
        max_traces: 100000

connectors:
  spanmetrics:

receivers:
  otlp:
    protocols:
      grpc:
      http:

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: memstore
  prometheus: 
    endpoint: "0.0.0.0:8889"
