service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter, spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics] 
      exporters: [prometheus] 


extensions:
  jaeger_query:
    trace_storage: some_storage
    metrics_storage: prometheus
  jaeger_storage:
    backends:
      some_storage:
        memory:
          max_traces: 100000
        prometheus:

connectors:
  spanmetrics:

receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some_storage
    metrics_storage: prometheus
  prometheus: 
    endpoint: "0.0.0.0:8889"
