version: '2'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector
      entrypoint: ["/bin/bash", "/bin/wait-for-cassandra.sh", "/go/bin/collector-linux", "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
      ports:
        - "14269"
        - "14268:14268"
        - "14267"
        - "14250"
        - "9411:9411"
      volumes:
        - ./scripts/wait-for-cassandra.sh:/bin/wait-for-cassandra.sh
      restart: on-failure
      depends_on:
        - cassandra

    jaeger-query:
      image: jaegertracing/jaeger-query
      entrypoint: ["/bin/bash", "/bin/wait-for-cassandra.sh", "/go/bin/query-linux", "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
      ports:
        - "16686:16686"
        - "16687"
      volumes:
        - ./scripts/wait-for-cassandra.sh:/bin/wait-for-cassandra.sh
      restart: on-failure
      depends_on:
        - cassandra

    jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: ["--reporter.type=grpc", "--reporter.grpc.host-port=jaeger-collector:14250"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
      depends_on:
        - jaeger-collector

    cassandra:
      image: jaegertracing/jaeger-cassandra-schema
