version: '2'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector:latest
      dns_search: .  # Ensures unified DNS config.
      ports:
        - "14269"
        - "14268:14268"
        - "14267"
        - "9411:9411"
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-query:
      image: jaegertracing/jaeger-query:latest
      dns_search: .
      ports:
        - "16686:16686"
        - "16687"
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-agent:
      image: jaegertracing/jaeger-agent:latest
      dns_search: .
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
      depends_on:
        - jaeger-collector

    cassandra:
      image: cassandra:3.9
      dns_search: .

    cassandra-schema:
      image: jaegertracing/jaeger-cassandra-schema:latest
      dns_search: .
      depends_on:
        - cassandra

