All services will log to Loki via the loki docker logging plugin.
# To install run this on the host once:
# docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
version: '2'
services:
  grafana:
    image: grafana/grafana:7.1.4
    ports:
      - '3000:3000'
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  loki:
    image: grafana/loki:master
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '6831:6831'
      - '16686:16686'
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports:
      - "8080:8080"
    command: ["all"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

