hotrod:
  image: "jaegertracing/hotrod"
  ports:
    - "8080:8080"
    - "8081:8081"
    - "8082:8082"
    - "8083:8083"
  links:
    - jaeger-all

jaeger-all:
  image: jaegertracing/all-in-one
  ports:
    - "16686:16686"
    - "6831:6831/udp"
