service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      recievers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    trace_storage: cassandra_main
    trace_storage_archive: cassandra_archive
    ui_config: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    cassandra:
      cassandra_main:
        servers: http://127.0.0.1
        port: 9042
        proto_version: 4
      cassandra_archive:
        servers: http://127.0.0.1
        port: 9042
        proto_version: 4
recievers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: cassandra_main