service:
  extensions: [jaeger_storage, jaeger_query, remote_sampling]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, adaptive_sampling]
      exporters: [jaeger_storage_exporter]

extensions:
  remote_sampling:
    # You can either use file or adaptive sampling strategy in remote_sampling
    # file:
    #   path: ./cmd/jaeger/sampling-strategies.json
    adaptive:
      initial_sampling_probability: 0.1
      strategy_store: os_main
    http:
    grpc:

  jaeger_query:
    trace_storage: os_main
    trace_storage_archive: os_archive
    ui_config: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    opensearch:
      os_main:
        server_urls: http://localhost:9200
        log_level: "error"
        index_prefix: "jaeger-main"
        use_aliases: false
        create_mappings: true

      os_archive:
        server_urls: http://localhost:9200
        log_level: "error"
        index_prefix: "jaeger-main"
        use_aliases: false
        create_mappings: true

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  adaptive_sampling:
    strategy_store: os_main

exporters:
  jaeger_storage_exporter:
    trace_storage: os_main
