service:
  extensions: [jaeger_storage, jaeger_query, remote_sampling]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, adaptive_sampling]
      exporters: [jaeger_storage_exporter]

extensions:
  remote_sampling:
    # You can either use file or adaptive sampling strategy in remote_sampling
    # file:
    #   path: ./cmd/jaeger/sampling-strategies.json
    adaptive:
      initial_sampling_probability: 0.1
      strategy_store: cassandra_main
    http:
    grpc:

  jaeger_query:
    trace_storage: cassandra_main
    trace_storage_archive: cassandra_archive
    ui_config: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    cassandra:
      cassandra_main:
        servers: 127.0.0.1
        port: 9042
        keyspace: "jaeger_v1_dc1"
        connections_per_host: 2
        index:
          tags: true
          logs: true
          process_tags: true
      cassandra_archive:
        servers: 127.0.0.1
        port: 9042
        keyspace: "jaeger_v1_dc1"
        connections_per_host: 2
        index:
          tags: true
          logs: true
          process_tags: true
receivers:
  otlp:
    protocols:
      grpc:
      http:

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

processors:
  batch:
  adaptive_sampling:
    strategy_store: cassandra_main


exporters:
  jaeger_storage_exporter:
    trace_storage: cassandra_main
