service:
  extensions: [jaeger_storage, jaeger_query, remote_sampling]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch, adaptive_sampling]
      exporters: [jaeger_storage_exporter]

extensions:
  # health_check:
  # pprof:
  #   endpoint: 0.0.0.0:1777
  # zpages:
  #   endpoint: 0.0.0.0:55679

  jaeger_query:
    trace_storage: memstore
    trace_storage_archive: memstore_archive
    ui_config: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    memory:
      memstore:
        max_traces: 100000
      memstore_archive:
        max_traces: 100000

  remote_sampling:
    # You can either use file or adaptive sampling strategy in remote_sampling
    # file:
    #   path: ./cmd/jaeger/sampling-strategies.json
    adaptive:
      sampling_store: memstore
      initial_sampling_probability: 0.1
    http:
    grpc:

receivers:
  otlp:
    protocols:
      grpc:
      http:

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  batch:
  # Adaptive Sampling Processor is required to support adaptive sampling.
  # It expects remote_sampling extension with `adaptive:` config to be enabled.
  adaptive_sampling:

exporters:
  jaeger_storage_exporter:
    trace_storage: memstore
