service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    trace_storage: some_storage
    trace_storage_archive: another_storage
    ui_config: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    backends:
      some_storage:
        opensearch:
          index_prefix: "jaeger-main"

      another_storage:
        opensearch:
          index_prefix: "jaeger-main"
  
  healthcheckv2:
  use_v2: true
  http:
    endpoint: "0.0.0.0:13133"
  grpc:

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some_storage
