service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    trace_storage: cassandra_main
    trace_storage_archive: cassandra_archive
    ui_config: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    cassandra:
      cassandra_main:
        servers: 127.0.0.1
        port: 9042
        keyspace: "jaeger_v1_dc1"
        connections_per_host: 2
        index:
          tags: true
          logs: true
          process_tags: true
        username: "${CASSANDRA_MAIN_USERNAME}"
        password: "${CASSANDRA_MAIN_PASSWORD}"

      cassandra_archive:
        servers: 127.0.0.1
        port: 9042
        keyspace: "jaeger_v1_dc1"
        connections_per_host: 2
        index:
          tags: true
          logs: true
          process_tags: true
        username: "${CASSANDRA_ARCHIVE_USERNAME}"
        password: "${CASSANDRA_ARCHIVE_PASSWORD}"

receivers:
  otlp:
    protocols:
      grpc:
      http:

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: cassandra_main
