receivers:
  jaeger:
    remote_sampling:
      host_endpoint: localhost:5778
      fetch_endpoint: jaeger-collector:14250
    protocols:
      grpc:
        disabled: true
      thrift_compact:
      thrift_binary:

exporters:
  jaeger_cassandra:
    disabled: true
  jaeger:
    endpoint: jaeger-collector:14250

service:
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [jaeger]
