name: Block Main Branch PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  block_main_branch_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR branch
        id: check_branch
        run: |
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" && "${{ github.event.pull_request.head.ref }}" == 'main' ]]; then
            echo "PRs from the main branch of forked repositories are not allowed."
            exit 1
          fi

