name: CIT Elasticsearch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  elasticsearch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [5.6.16, 6.8.2, 7.3.0]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Install tools
      run: make install-ci

    - name: Run elasticsearch integration tests
      run: bash scripts/travis/es-integration-test.sh ${{ matrix.version }}
