name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - name: Run elasticsearch integration tests
          run: bash scripts/travis/es-integration-test.sh

        - name: Run elasticsearch opentelemetry integration tests
          run: bash scripts/travis/es-integration-test.sh

        - name: Run kafka integration tests
          run: bash scripts/travis/kafka-integration-test.sh

        - name: Run cassandra integration tests
          run: bash scripts/travis/cassandra-integration-test.sh

        - name: Run in-memory and badger integration tests
          run: make mem-and-badger-storage-integration-test

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup go env
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: ${{ matrix.name }}
      run: ${{ matrix.run }}
