name: Memory and Badger Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  memory-badger:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup go env
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Run in-memory and badger integration tests
      run: make mem-and-badger-storage-integration-test
