name: v1 - CIT Kafka

on:
  push:
    branches: [ master ]
    paths-ignore:
    - v2/**
  pull_request:
    branches: [ master ]
    paths-ignore:
    - v2/**

jobs:
  kafka:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Run kafka integration tests
      run: bash scripts/kafka-integration-test.sh
