name: v2 - Tests

on:
  push:
    branches:
    - master
    - main
    paths:
      - v2/**
  pull_request:
    branches:
    - master
    - main
    paths:
      - v2/**

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      
      - name: Basic Checks
        run: make test
